
import java.awt.Color;
import javax.swing.ImageIcon;


public class NesneSecimi extends javax.swing.JFrame {
    String[] nesneler=new String[5];
    ImageIcon img1=new ImageIcon("/tas3.png");
    ImageIcon img2=new ImageIcon("/kagıt3.png");
    ImageIcon img3=new ImageIcon("/makas3.png");
    public int i=0;
    int secim=0;
    /**
     * Creates new form NesneSecimi
     */
    public NesneSecimi() {
        initComponents();
        getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TasButton = new javax.swing.JButton();
        KagitButton = new javax.swing.JButton();
        MakasButton = new javax.swing.JButton();
        Secim2 = new javax.swing.JLabel();
        Secim1 = new javax.swing.JLabel();
        Secim3 = new javax.swing.JLabel();
        Secim4 = new javax.swing.JLabel();
        Secim5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        YerlestirButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        İleriButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tas2.png"))); // NOI18N
        TasButton.setFocusPainted(false);
        TasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TasButtonActionPerformed(evt);
            }
        });

        KagitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kagıt2.png"))); // NOI18N
        KagitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KagitButtonActionPerformed(evt);
            }
        });

        MakasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makas2.png"))); // NOI18N
        MakasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakasButtonActionPerformed(evt);
            }
        });

        Secim2.setText("a");

        Secim1.setText("a");

        Secim3.setText("a");

        Secim4.setText("a");

        Secim5.setText("a");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Seçim 1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Seçim 2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Seçim 3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Seçim 4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Seçim 5");

        YerlestirButton.setBackground(new java.awt.Color(204, 204, 204));
        YerlestirButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        YerlestirButton.setText("---->");
        YerlestirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YerlestirButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("YERLEŞTİR");

        İleriButton.setBackground(new java.awt.Color(51, 51, 255));
        İleriButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        İleriButton.setText("İLERİ");
        İleriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                İleriButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KagitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(YerlestirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(İleriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Secim5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Secim4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Secim3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Secim1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Secim2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Secim1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Secim2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Secim3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Secim4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Secim5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YerlestirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(KagitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(İleriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(MakasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        KagitButton.getAccessibleContext().setAccessibleName("KagitButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TasButtonActionPerformed
        i++;
        nesneler[secim]="Tas";
        if(secim==0)
        {
            
            Secim1.setText(nesneler[secim]);
            Secim1.setVisible(false);
        }
        else if(secim==1)
        {
            
            Secim2.setText(nesneler[secim]);
            Secim2.setVisible(false);
        }
        else if(secim==2)
        {
            
            Secim3.setText(nesneler[secim]);
            Secim3.setVisible(false);
        }
        else if(secim==3)
        {
            
            Secim4.setText(nesneler[secim]);
            Secim4.setVisible(false);
        }
        else if(secim==4)
        {
            
            Secim5.setText(nesneler[secim]);
            Secim5.setVisible(false);
        }
        
        if(i==5){
            TasButton.setEnabled(false);
            KagitButton.setEnabled(false);
            MakasButton.setEnabled(false);
        }
        secim++;
    }//GEN-LAST:event_TasButtonActionPerformed

    private void KagitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KagitButtonActionPerformed
        i++;
        nesneler[secim]="Kağıt";
        if(secim==0)
        {
            Secim1.setText(nesneler[secim]);
            Secim1.setVisible(false);
        }
        else if(secim==1)
        {         
            Secim2.setText(nesneler[secim]);
            Secim2.setVisible(false);
        }
        else if(secim==2)
        {           
            Secim3.setText(nesneler[secim]);
            Secim3.setVisible(false);
        }
        else if(secim==3)
        {    
            Secim4.setText(nesneler[secim]);
            Secim4.setVisible(false);
        }
        else if(secim==4)
        {    
            Secim5.setText(nesneler[secim]);
            Secim5.setVisible(false);
        }
        if(i==5){
            TasButton.setEnabled(false);
            KagitButton.setEnabled(false);
            MakasButton.setEnabled(false);
        }
        secim++;
    }//GEN-LAST:event_KagitButtonActionPerformed

    private void MakasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakasButtonActionPerformed
        i++;
        nesneler[secim]="Makas";
        if(secim==0)
        {
            Secim1.setText(nesneler[secim]);
            Secim1.setVisible(false);
        }
        else if(secim==1)
        {   
            Secim2.setText(nesneler[secim]);
            Secim2.setVisible(false);
        }
        else if(secim==2)
        {   
            Secim3.setText(nesneler[secim]);
            Secim3.setVisible(false);
        }
        else if(secim==3)
        {      
            Secim4.setText(nesneler[secim]);
            Secim4.setVisible(false);
        }
        else if(secim==4)
        {     
            Secim5.setText(nesneler[secim]);
            Secim5.setVisible(false);
        }
        if(i==5){
            TasButton.setEnabled(false);
            KagitButton.setEnabled(false);
            MakasButton.setEnabled(false);
        }
        secim++;
    }//GEN-LAST:event_MakasButtonActionPerformed

    private void YerlestirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YerlestirButtonActionPerformed
        Secim1.setVisible(true);
        Secim2.setVisible(true);
        Secim3.setVisible(true);
        Secim4.setVisible(true);
        Secim5.setVisible(true);
    }//GEN-LAST:event_YerlestirButtonActionPerformed

    private void İleriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_İleriButtonActionPerformed
        
    }//GEN-LAST:event_İleriButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NesneSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NesneSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NesneSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NesneSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NesneSecimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KagitButton;
    private javax.swing.JButton MakasButton;
    private javax.swing.JLabel Secim1;
    private javax.swing.JLabel Secim2;
    private javax.swing.JLabel Secim3;
    private javax.swing.JLabel Secim4;
    private javax.swing.JLabel Secim5;
    private javax.swing.JButton TasButton;
    private javax.swing.JButton YerlestirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton İleriButton;
    // End of variables declaration//GEN-END:variables
}
